pw_cpu_exception: Declare State as part of the entry facade
Updates the pw_cpu_exception's entry facade/backend to explicitly
provide the pw_cpu_exception_State structure instead of forward
declaring it and incidentally providing it through the optional,
but previously actually required due to this, support backend.

In order to do this without creating circular dependencies all over,
the entry implementation is linked in through link deps just like
log and assert.

Also cleans up some build rules.

Change-Id: I763df687da09e3c67e76db07e165d2387cf06346
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/74181
Pigweed-Auto-Submit: Ewout van Bekkum <ewout@google.com>
Reviewed-by: Armando Montanez <amontanez@google.com>
Commit-Queue: Auto-Submit <auto-submit@pigweed.google.com.iam.gserviceaccount.com>