pw_bytes: Revert moving to whole_static_libs in Android.bp
This can cause duplicate symbol errors in build

```
ld.lld: error: duplicate symbol: pw_StatusString
>>> defined at status.cc:21 (external/pigweed/pw_status/status.cc:21)
>>>            status.o:(pw_StatusString) in archive out/soong/.intermediates/external/pigweed/pw_bytes/pw_bytes/linux_glibc_x86_static/pw_bytes.a
>>> defined at status.cc:21 (external/pigweed/pw_status/status.cc:21)
>>>            status.o:(.text+0x0) in archive out/soong/.intermediates/external/pigweed/pw_status/pw_status/linux_glibc_x86_static/pw_status.a
```

Change-Id: Ibde403427a07034a5c27b85c1914d97e44fe4205
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/245753
Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
Docs-Not-Needed: Austin Foxley <afoxley@google.com>
Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Pigweed-Auto-Submit: Austin Foxley <afoxley@google.com>
Reviewed-by: Taylor Cramer <cramertj@google.com>
Commit-Queue: Austin Foxley <afoxley@google.com>