pw_sync_stl: Android.bp: Add missing dependency on pw_sync_headers
With the addition of pw_android_common_backends, targets might end up
including pw_sync_stl_defaults without really needing it, and thus, not
already depending on pw_sync_headers. If this happens, The pw_sync_stl
sources (pw_sync_stl_src_files) will be compiled without the pw_sync
headers being available, leading to errors like this:

external/pigweed/pw_sync_stl/binary_semaphore.cc:15:10: fatal error:
'pw_sync/binary_semaphore.h' file not found

Since the source files use the pw_sync header files, the rule should
include them, too.

Test: Compile a library (pw_digital_io_linux) depending on
      pw_android_common_backends but not pw_sync.
Change-Id: I4f0f7ef118ba41df2b870beeceb09e0107451b13
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/197030
Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
Reviewed-by: Carlos Chinchilla <cachinchilla@google.com>
Commit-Queue: Jonathon Reinhart <jrreinhart@google.com>