pw_assert_log: Depend on pw_log_headers in Android.bp
If the including rule didn't already depend on pw_log_headers, then
pw_log header files would not be found, e.g.:

  In file included from external/pigweed/pw_digital_io/public/pw_digital_io/digital_io.h:16:
  In file included from external/pigweed/pw_assert/public/pw_assert/check.h:122:
  In file included from external/pigweed/pw_assert_log/check_backend_public_overrides/pw_assert_backend/check_backend.h:20:
  external/pigweed/pw_assert_log/public/pw_assert_log/check_log.h:16:10: fatal error: 'pw_log/levels.h' file not found
     16 | #include "pw_log/levels.h"
        |          ^~~~~~~~~~~~~~~~~

Test: Build Android target depending on pw_assert_log_headers.
Change-Id: Iae59a16d97460684f874b592b3156102d43d610d
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/194434
Pigweed-Auto-Submit: Jonathon Reinhart <jrreinhart@google.com>
Reviewed-by: Carlos Chinchilla <cachinchilla@google.com>
Commit-Queue: Auto-Submit <auto-submit@pigweed-service-accounts.iam.gserviceaccount.com>