pw_snaphot: Fix processor argparse types
This fixes two bytes-vs-str related issues:

1. `--out-file` should be a text file, not a binary file, indicated by
   the `out_file: TextIO` parameter of _load_and_dump_snapshots().

   This fixes the following error when running with no --out-file
   argument:

   TypeError: a bytes-like object is required, not 'str'

2. Change `--token-db` just a string, and update the
   _load_and_dump_snapshots() parameter accordingly.
   pw_tokenizer.Detokenizer() accepts plain paths, and intelligently
   opens files.

   This avoids the following error down in elf_reader.py when passing an
   ELF (binary):

   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in
   position 100: invalid continuation byte

Test: python3 -m pw_snapshot.processor --token-db firmware.elf crash.binpb
Change-Id: Ida4f2a0d180a99605614f61e4a4da70b5f3bfbf9
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/301134
Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
Commit-Queue: Jonathon Reinhart <jrreinhart@google.com>
Docs-Not-Needed: Jonathon Reinhart <jrreinhart@google.com>
Tests-Not-Needed: Jonathon Reinhart <jrreinhart@google.com>
Reviewed-by: Carlos Chinchilla <cachinchilla@google.com>
Copybara-Verified: Copybara Prod <copybara-worker-blackhole@google.com>