pw_unit_test: Fix -Waddress warning when verifying RUN_ALL_TESTS
When Google Test back-end is used for pw_unit_test GCC reports warning
as follows:

pw_unit_test/public/pw_unit_test/framework.h:181:30: error: the address of 'int RUN_ALL_TESTS()' will never be NULL [-Werror=address]

This happens only with Google Test back-end, because pw_unit_test uses
"#define RUN_ALL_TESTS() ..." and in such case the static_assert is not
used.

Change-Id: Ia8918439bdc89e11a8a4dc416fe93f7e3daf51b5
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/243133
Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Reviewed-by: Keir Mierle <keir@google.com>
Commit-Queue: Keir Mierle <keir@google.com>
Docs-Not-Needed: Arkadiusz Bokowy (Arkq) <arkadiusz.bokowy@gmail.com>
Reviewed-by: Arkadiusz Bokowy (Arkq) <arkadiusz.bokowy@gmail.com>
Reviewed-by: Andrei Litvin <andreilitvin@google.com>