pw_protobuf_compiler: Add a no_prefix test
This adds a test that fails due to the bazel prefix logic being broken.
A subsequent patch will fix it.

Bug: 328311416
Test:
```
bazel test //pw_protobuf_compiler/...
Starting local Bazel server and connecting to it...
ERROR: pw_protobuf_compiler/BUILD.bazel:44:14: in //pw_protobuf_compiler:pw_proto_library.bzl%_pwpb_proto_compiler_aspect aspect on proto_library rule //pw_protobuf_compiler:pwpb_test_proto_no_prefix:
Traceback (most recent call last):
	File "pw_protobuf_compiler/pw_proto_library.bzl", line 336, column 48, in _proto_compiler_aspect_impl
		out_file = ctx.actions.declare_file("{}/{}".format(
Error in declare_file: the output artifact '/pwpb_test_no_prefix.pwpb.h' is not under package directory 'pw_protobuf_compiler' for target '//pw_protobuf_compiler:pwpb_test_proto_no_prefix'
```

Change-Id: I4111f3061807ce09aecdc158fd1c9702b653567a
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/208138
Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Reviewed-by: Austin Foxley <afoxley@google.com>
Commit-Queue: Eric Rahm <erahm@google.com>
Reviewed-by: Ted Pudlik <tpudlik@google.com>