pw_kernel: Improve system_generator error handling
Turns a debug printed TOML error into a more readable:

```
Error: Failed to parse config file

Caused by:
    TOML parse error at line 33, column 1
       |
    33 | {name = "thread one a", stack_size_bytes = 1024}
       | ^
    invalid key
```

Change-Id: I5c66af6b7e3ce8fb18c295fed3134d6c73b7b170
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/312752
Reviewed-by: Dave Roth <davidroth@google.com>
Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Docs-Not-Needed: Erik Gilling <konkers@google.com>
Commit-Queue: Erik Gilling <konkers@google.com>